config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :arts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
    belongs_to :artist
    validates :art_name, format: {with: /[a-zA-Z]/},uniqueness: true
    validates :price, :numericality => {greater_than: 0}
    validates :year, presence: true, :numericality => true, length: {is: 4}
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :arts
    validates :age, numericality: true
    validates :name, format: {with: /[a-zA-z]/},uniqueness: true
    validates :experience_level, presence: true, :numericality => {:less_than => :age}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all
    end

    def show
        # params: { "id" => "1" }
        id = params["id"] # "1"
        
        @artist = Artist.find(id)
    end 
    
    def new
        @artist = Artist.new
    end

    def create
            @artist = Artist.create(artist_params)
            if  @artist.save   
                flash[:notice] = "A new Artist has been created."
                redirect_to @artist
            else
                render action: :new
            end
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def update
        @artist = Artist.find(params[:id])
        if @artist.update(artist_params)
            flash[:notice] = "Artist has been updated."
            redirect_to @artist # || artist_path(@artist) || "/artists/#{@artist.id}"
        else
            render action: :edit
        end
    end

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        flash[:notice] = "The selected artist is deleted."
        redirect_to artists_path
    end
    
    private
    def artist_params
        params.require(:artist).permit(:name,:age,:experience_level)
    end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
    def index
        @arts = Art.all
    end

    def new
        @art = Art.new
    end

    def create
        @art = Art.create(art_params)
        if @art.save
            flash[:notice] = "A new Art has been created."
            redirect_to "/arts"
        else
            render action: :new
        end

    end
    

    def show
        @art = Art.find(params[:id])
              
    end

    def edit
        @art = Art.find(params[:id])
    end

    def update
        @art = Art.find(params["id"])
        if @art.update(art_params)
            flash[:notice] = "Art has been updated."
            redirect_to @art
        else
            render action: :edit
        end
    end

    def destroy
        @art = Art.find(params[:id])
        @art.destroy
        flash[:notice] = "Art has been deleted."
        redirect_to "/arts"
        
    end
    private 
    def art_params
        params.require(:art).permit(:artist_id, :art_name, :price, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_errors.erb
<% if @artist.errors.present? %>

  <ul>Fix following errors
    <% for error in @artist.errors.full_messages %>
    <div style="color: #FF6666">
      <li><%= error %></li>
    </div>
    <% end %>
  </ul> 

<% end %>

app/views/artists/_form.erb
<%= form_for @artist do |f| %>
    <table>
        <tr>
            <td>Name: </td>
            <td><%= f.text_field :name %></td>
        </tr>

        <tr>
            <td>Age: </td>
            <td><%= f.text_field :age %></td>
        </tr>

        <tr>
            <td>Experience_level </td>
            <td><%= f.number_field :experience_level %></td>
        </tr>

        <tr>
            <td></td>
            <td><%= f.submit %></td>
        </tr>
    </table> 
<% end %>

app/views/artists/edit.erb
<h2>Edit Artist details</h2>

<%= render "errors" %>

<%= render "form" %>

app/views/artists/index.erb
 <%= render "flash" %>
 
 <h1>List of artists</h1>

 <table border="1" width="500">
    <tr>
        <th width = "30%" >Name</th>
        <th width = "15%" >Age</th>
        <th width = "15%" >Experience</th>
        <th width = "40%" >Actions</th>
    </tr>
    
    <tbody>
        <% for artist in @artists do%>
            <tr>
                <td><%= artist.name %></td>
                <td><%= artist.age %></td>
                <td><%= artist.experience_level %></td>
                <td>
                    <%= link_to("view","/artists/#{artist.id}") %> |
                    <%= link_to("edit","/artists/#{artist.id}/edit") %> |
                    <%= link_to("Delete","/artists/#{artist.id}") %>
                </td>
            </tr>
        <% end%> 
          
    </tbody>
 </table>

<%= link_to("Create New Artist",new_artist_path) %>

 

app/views/artists/new.erb
<%#= render "flash" %>
<%= render "errors" %>
<%= render "form" %>

app/views/artists/show.erb
<h1>Artist's details</h1>
<%= render "flash" %>

<table border = "1" width = "500">
    <tr>
        <th width = "30%" >Name</th>
        <th width = "15%" >Age</th>
        <th width = "15%" >Experience</th>
        <th width = "40%" >Actions</th>
    </tr>

    <tbody>
        <tr>
            <td><%= @artist[:name] %></td>
            <td><%= @artist[:age] %></td>
            <td><%= @artist[:experience_level] %></td>
            <td><%= link_to("Edit","/artists/#{@artist.id}/edit")%> | <%= link_to("Back","/artists")%></td>
        </tr>
      
    </tbody>
</table>

<br>

<%= form_for(@artist,:html => {method: :delete}) do |f|%>
    <%= f.submit "Delete" %>
<%end%>

app/views/arts/_errors.erb
<% if @art.errors.present? %>

  <ul>Fix following errors
    <% for error in @art.errors.full_messages %>
    <div style="color: #FF6666">
      <li><%= error %></li>
    </div>
    <% end %>
  </ul> 

<% end %>

app/views/arts/_flash.erb
<% flash.each do |type, msg|%>
    <div style="color: #FF6666">
        <%= msg %>
    </div>
<% end %>

app/views/arts/_form.erb
<%= form_for @art do |f| %>
    <table>
        <tr>
            <td>Art_id:</td>
            <td><%= f.number_field :artist_id %></td>
        </tr>
        <tr>
            <td>Name of the Art:</td>
            <td><%= f.text_field :art_name%></td>
        </tr>
        <tr>
            <td>Price of the Art:</td>
            <td><%= f.number_field :price %></td>
        </tr>
        <tr>
            <td>Year:</td>
            <td><%= f.number_field :year %></td>
        </tr>
        <tr>
            <td></td>
            <td><%=f.submit %></td>     
        </tr>
    </table>
<% end %>
<%= link_to("Back to the arts list", arts_path) %>

app/views/arts/edit.erb
<h1>Edit Art </h1>
<%= render "errors" %>
<%= render "form" %>
<tr>
    <%= form_for(@art,:html => {method: :delete}) do |f|%>
        <%= f.submit "Delete Art" %>
    <% end %> 
</tr>   

app/views/arts/index.erb
<%= render "flash" %>
<h1>List of Arts</h1>

<table border = "1" width = "500">
    <tr>
        <th width = "10%" > Artist_Id </th><br>
        <th width = "40%" > Art Name </th><br>
        <th width = "10%" > Price </th><br>
        <th width = "20%" > Year </th>
        <th width = "20" > Actions </th>
    </tr>
    <tbody>
        <% for art in @arts do %>
            <tr>
                <td><%= art.artist_id %></td>
                <td><%= art.art_name %></td>
                <td><%= art.price %></td>
                <td><%= art.year %></td>
                <td><%= link_to("open","/arts/#{art[:id]}") %>|
                <%= link_to("Edit","/arts/#{art[:id]}/edit")%> 

                </td> 
            </tr>
        <% end %>
    </tbody>    
</table>
    <%= link_to("Create New Art",new_art_path) %>

app/views/arts/new.erb
<%= render "errors" %>
<%= render "form" %>

app/views/arts/show.erb
<%= render "flash"%>
<h1>Details of Art</h1>
<table border = "1", width = "500" >
    <tr>
        <th>Art_id</th>
        <th>Art Name</th>
        <th>Year</th>
        <th>Actions</th>
    </tr>
    <tbody>
        <tr>
            <td><%= @art[:artist_id] %></td>
            <td><%= @art[:art_name] %></td>
            <td><%= @art[:price] %></td>
            <td><%= @art[:year] %></td>
            <td><%= link_to("Edit","/arts/#{@art[:id]}/edit")%></td>|
            <td><%= link_to("Back to the list",arts_path)%></td>
            
        </tr>
    </tbody>
</table>
<%= form_for(@art,:html => {method: :delete}) do |f|%>
    <%= f.submit "Delete" %>
<% end %>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Art App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>